// Generated by build.rs using official Google protobuf-codegen v4
// Each file is wrapped in an internal module and re-exported with `pub use *`
// so that super:: cross-references between proto files resolve correctly.

#[allow(nonstandard_style, mismatched_lifetime_syntaxes)]
pub mod internal_do_not_use_OpenApiCommonModelMessages {
    include!(concat!(
        env!("OUT_DIR"),
        "/protobuf_generated/OpenApiCommonModelMessages.u.pb.rs"
    ));
}
#[allow(unused_imports, nonstandard_style)]
pub use internal_do_not_use_OpenApiCommonModelMessages::*;

#[allow(nonstandard_style, mismatched_lifetime_syntaxes)]
pub mod internal_do_not_use_OpenApiModelMessages {
    include!(concat!(
        env!("OUT_DIR"),
        "/protobuf_generated/OpenApiModelMessages.u.pb.rs"
    ));
}
#[allow(unused_imports, nonstandard_style)]
pub use internal_do_not_use_OpenApiModelMessages::*;

#[allow(nonstandard_style, mismatched_lifetime_syntaxes)]
pub mod internal_do_not_use_OpenApiCommonMessages {
    include!(concat!(
        env!("OUT_DIR"),
        "/protobuf_generated/OpenApiCommonMessages.u.pb.rs"
    ));
}
#[allow(unused_imports, nonstandard_style)]
pub use internal_do_not_use_OpenApiCommonMessages::*;

#[allow(nonstandard_style, mismatched_lifetime_syntaxes)]
pub mod internal_do_not_use_OpenApiMessages {
    include!(concat!(
        env!("OUT_DIR"),
        "/protobuf_generated/OpenApiMessages.u.pb.rs"
    ));
}
#[allow(unused_imports, nonstandard_style)]
pub use internal_do_not_use_OpenApiMessages::*;
