// Integration tests for tree models
// Tests full training and prediction pipeline with real data
//
// TODO(real-data): the comment above lies — `create_sample_data` (and
// any sibling helpers below) generate synthetic classification data
// with deterministic linear ramps and modular labels. Replace every
// sample-generator in this file with a cTrader historical sample
// (e.g. EURUSD M15 features → 3-class labels generated by the
// production label_builder over real OHLCV) so the test exercises the
// shape and noise distribution the LightGBM / XGBoost experts will
// see in production.

#[cfg(all(test, feature = "lightgbm"))]
mod lightgbm_tests {
    use neoethos_models::tree_models::config::ParamValue;
    use neoethos_models::tree_models::{LightGBMExpert, TreeModel};
    use polars::prelude::Column;
    use polars::prelude::*;
    use std::collections::HashMap;

    fn cpu_lightgbm_params() -> HashMap<String, ParamValue> {
        HashMap::from([
            ("device".to_string(), ParamValue::String("cpu".to_string())),
            ("gpu_only".to_string(), ParamValue::Bool(false)),
        ])
    }

    fn create_sample_data() -> (DataFrame, Series) {
        // Create synthetic classification data
        let n_samples = 1000;
        let n_features = 10;

        // Generate random features
        let mut features: Vec<Series> = Vec::new();
        for i in 0..n_features {
            let data: Vec<f64> = (0..n_samples)
                .map(|j| (j as f64 * 0.1 + i as f64) % 10.0)
                .collect();
            features.push(Series::new(format!("feature_{}", i).into(), data));
        }

        let df = DataFrame::new(features.into_iter().map(Column::from).collect()).unwrap();

        // Generate labels {-1, 0, 1} based on features
        let labels: Vec<i64> = (0..n_samples)
            .map(|i| {
                let val = i % 3;
                match val {
                    0 => -1,
                    1 => 0,
                    _ => 1,
                }
            })
            .collect();
        let labels_series = Series::new("label".into(), labels);

        (df, labels_series)
    }

    #[test]
    fn test_lightgbm_train_predict() {
        // Create sample data
        let (df, labels) = create_sample_data();

        // Split into train/test
        let n_train = 800;
        let train_df = df.slice(0, n_train);
        let test_df = df.slice(n_train as i64, 200);
        let train_labels = labels.slice(0, n_train);

        // Create and train model
        let mut model = LightGBMExpert::new(1, Some(cpu_lightgbm_params()));

        let result = model.fit(&train_df, &train_labels);
        assert!(
            result.is_ok(),
            "Training should succeed: {:?}",
            result.err()
        );

        // Predict
        let predictions = model.predict_proba(&test_df);
        assert!(
            predictions.is_ok(),
            "Prediction should succeed: {:?}",
            predictions.err()
        );

        let probs = predictions.unwrap();
        assert_eq!(probs.shape(), &[200, 3], "Output should be [n_samples, 3]");

        // Check probabilities sum to ~1
        for row in probs.outer_iter() {
            let sum: f32 = row.iter().sum();
            assert!(
                (sum - 1.0).abs() < 0.01,
                "Probabilities should sum to 1, got {}",
                sum
            );
        }

        // Check probabilities are in [0, 1]
        for &prob in probs.iter() {
            assert!(
                (0.0..=1.0).contains(&prob),
                "Probability should be in [0, 1], got {}",
                prob
            );
        }
    }

    #[test]
    fn test_lightgbm_save_load() {
        use std::fs;
        use std::path::Path;

        let (df, labels) = create_sample_data();
        let train_df = df.slice(0, 800);
        let train_labels = labels.slice(0, 800);

        // Train model
        let mut model = LightGBMExpert::new(1, Some(cpu_lightgbm_params()));
        model.fit(&train_df, &train_labels).unwrap();

        // Save model
        let model_path = Path::new("test_lightgbm_model_artifact");
        let result = model.save(model_path);
        assert!(result.is_ok(), "Save should succeed: {:?}", result.err());

        // Load model
        let mut loaded_model = LightGBMExpert::new(1, None);
        let result = loaded_model.load(model_path);
        assert!(result.is_ok(), "Load should succeed: {:?}", result.err());

        // Predict with loaded model
        let test_df = df.slice(800, 200);
        let predictions = loaded_model.predict_proba(&test_df);
        assert!(
            predictions.is_ok(),
            "Prediction with loaded model should succeed"
        );

        // Cleanup
        let _ = fs::remove_dir_all(model_path);
    }

    #[test]
    fn test_label_remapping() {
        use neoethos_models::tree_models::remap_labels_to_contiguous;

        // Test with -1, 0, 1 labels
        let labels = Series::new("label".into(), &[-1i64, 0, 1, -1, 0, 1, 1, 0, -1]);
        let (remapped, mapping) = remap_labels_to_contiguous(&labels).unwrap();

        // Check remapping: -1 -> 0, 0 -> 1, 1 -> 2
        assert_eq!(remapped.as_slice().unwrap(), &[0, 1, 2, 0, 1, 2, 2, 1, 0]);
        assert_eq!(mapping.get(&-1), Some(&0));
        assert_eq!(mapping.get(&0), Some(&1));
        assert_eq!(mapping.get(&1), Some(&2));
    }

    #[test]
    fn test_output_reordering() {
        use ndarray::Array2;
        use neoethos_models::tree_models::reorder_to_neutral_buy_sell;

        // Binary classification (2 classes — Buy / Sell, no Neutral).
        // The production contract for the 2-column case is: there is no
        // neutral signal at all, so the safe projection into the
        // (Neutral, Buy, Sell) 3-column shape is `col_0 = 1.0` (max
        // neutral) and the input columns are deliberately discarded.
        // That is what the matching unit test in `tree_models/common.rs`
        // (`reorder_to_neutral_buy_sell_two_columns_returns_neutral_rows`)
        // asserts, and it is what the live trading path consumes: a
        // binary model does NOT have authority to fire a directional
        // signal in a 3-class consumer, so the consumer sees neutral.
        let probs_binary =
            Array2::from_shape_vec((3, 2), vec![0.7, 0.3, 0.6, 0.4, 0.8, 0.2]).unwrap();
        let reordered = reorder_to_neutral_buy_sell(probs_binary, None);
        assert_eq!(reordered.shape(), &[3, 3]);
        for row in 0..3 {
            assert_eq!(reordered[[row, 0]], 1.0, "row {row}: neutral");
            assert_eq!(reordered[[row, 1]], 0.0, "row {row}: buy");
            assert_eq!(reordered[[row, 2]], 0.0, "row {row}: sell");
        }

        // Test multiclass (3 classes) with known class order
        let probs_multi =
            Array2::from_shape_vec((2, 3), vec![0.1, 0.2, 0.7, 0.5, 0.3, 0.2]).unwrap();

        let reordered = reorder_to_neutral_buy_sell(probs_multi.clone(), Some(vec![0, 1, 2]));
        // With classes [0, 1, 2] (Neutral, Buy, Sell), output should match
        assert_eq!(reordered[[0, 0]], 0.1); // Neutral
        assert_eq!(reordered[[0, 1]], 0.2); // Buy
        assert_eq!(reordered[[0, 2]], 0.7); // Sell
    }

    #[test]
    fn test_time_feature_augmentation() {
        use neoethos_models::tree_models::augment_time_features;

        // Create DataFrame with 'close' column
        let close_prices: Vec<f64> = vec![100.0, 101.0, 99.0, 102.0, 103.0, 101.0, 104.0, 105.0];
        let volume: Vec<f64> = vec![
            1000.0, 1100.0, 900.0, 1200.0, 1300.0, 1100.0, 1400.0, 1500.0,
        ];

        let df = DataFrame::new(vec![
            Series::new("close".into(), close_prices).into(),
            Series::new("volume".into(), volume).into(),
        ])
        .unwrap();

        let augmented = augment_time_features(df);
        assert!(
            augmented.is_ok(),
            "Augmentation should succeed: {:?}",
            augmented.err()
        );

        let augmented_df = augmented.unwrap();

        // Check that new columns were added
        assert!(
            augmented_df.column("ret1").is_ok(),
            "ret1 column should exist"
        );
        assert!(
            augmented_df.column("ret1_lag1").is_ok(),
            "ret1_lag1 column should exist"
        );
        assert!(
            augmented_df.column("vol14").is_ok() || augmented_df.height() < 14,
            "vol14 should exist if enough data"
        );

        // Original columns should still exist
        assert!(
            augmented_df.column("close").is_ok(),
            "close column should exist"
        );
        assert!(
            augmented_df.column("volume").is_ok(),
            "volume column should exist"
        );
    }

    #[test]
    fn test_gpu_only_mode() {
        let (df, labels) = create_sample_data();
        let train_df = df.slice(0, 800);
        let train_labels = labels.slice(0, 800);

        let mut model = LightGBMExpert::new(
            1,
            Some(HashMap::from([
                ("device".to_string(), ParamValue::String("gpu".to_string())),
                ("gpu_only".to_string(), ParamValue::Bool(true)),
            ])),
        );

        let result = model.fit(&train_df, &train_labels);
        if let Err(err) = result {
            assert!(
                err.to_string()
                    .contains("gpu-only mode requested but no GPU is available"),
                "unexpected gpu-only error: {err}"
            );
        }
    }
}

#[cfg(all(test, feature = "xgboost"))]
mod xgboost_tests {
    use neoethos_models::tree_models::config::ParamValue;
    use neoethos_models::tree_models::{TreeModel, XGBoostExpert};
    use polars::prelude::Column;
    use polars::prelude::*;
    use std::collections::HashMap;

    #[test]
    fn test_xgboost_basic() {
        // Similar test to LightGBM but for XGBoost
        let n_samples = 500;
        let n_features = 5;

        let mut features: Vec<Series> = Vec::new();
        for i in 0..n_features {
            let data: Vec<f64> = (0..n_samples)
                .map(|j| (j as f64 * 0.1 + i as f64) % 10.0)
                .collect();
            features.push(Series::new(format!("feature_{}", i).into(), data));
        }

        let df = DataFrame::new(features.into_iter().map(Column::from).collect()).unwrap();
        let labels: Vec<i64> = (0..n_samples)
            .map(|i| match i % 3 {
                0 => -1,
                1 => 0,
                _ => 1,
            })
            .collect();
        let labels_series = Series::new("label".into(), labels);

        let train_df = df.slice(0, 400);
        let test_df = df.slice(400, 100);
        let train_labels = labels_series.slice(0, 400);

        let mut model = XGBoostExpert::new(
            1,
            Some(HashMap::from([
                ("device".to_string(), ParamValue::String("cpu".to_string())),
                ("gpu_only".to_string(), ParamValue::Bool(false)),
            ])),
        );

        let result = model.fit(&train_df, &train_labels);
        assert!(
            result.is_ok(),
            "XGBoost training should succeed: {:?}",
            result.err()
        );

        let predictions = model.predict_proba(&test_df);
        assert!(
            predictions.is_ok(),
            "XGBoost prediction should succeed: {:?}",
            predictions.err()
        );

        let probs = predictions.unwrap();
        assert_eq!(probs.shape(), &[100, 3]);
    }
}

#[cfg(all(test, feature = "catboost"))]
mod catboost_tests {
    use neoethos_models::tree_models::{CatBoostExpert, TreeModel};
    use polars::prelude::Column;
    use polars::prelude::*;
    use std::process::Command;

    fn catboost_cli_available() -> bool {
        for candidate in ["catboost", "catboost.exe"] {
            if Command::new(candidate)
                .arg("--version")
                .output()
                .map(|output| output.status.success())
                .unwrap_or(false)
            {
                return true;
            }
        }
        false
    }

    #[test]
    fn test_catboost_training_contract() {
        let features = vec![Series::new("f1".into(), vec![1.0, 2.0, 3.0])];
        let df = DataFrame::new(features.into_iter().map(Column::from).collect()).unwrap();
        let labels = Series::new("label".into(), vec![-1i64, 0, 1]);

        let mut model = CatBoostExpert::new(1);
        let result = model.fit(&df, &labels);

        if catboost_cli_available() {
            assert!(
                result.is_ok(),
                "CatBoost training should succeed when CLI is available: {:?}",
                result.err()
            );
            let predictions = model.predict_proba(&df);
            assert!(
                predictions.is_ok(),
                "CatBoost prediction should succeed after training: {:?}",
                predictions.err()
            );
            assert_eq!(predictions.unwrap().shape(), &[3, 3]);
        } else {
            assert!(
                result.is_err(),
                "CatBoost training should fail cleanly when CLI is unavailable"
            );
            let err_msg = result.err().unwrap().to_string();
            assert!(
                err_msg.contains("CatBoost CLI")
                    || err_msg.contains("FOREX_BOT_CATBOOST_EXECUTABLE")
                    || err_msg.contains("CATBOOST_EXECUTABLE"),
                "Error should mention missing CatBoost CLI, got: {err_msg}"
            );
        }
    }
}
