; scripts/gemma_model_install.nsh — NSIS install-time hook that fetches the
; bundled Gemma 4 abliterated GGUF from HuggingFace when the user installs
; the Lite SKU of NeoEthos. Hooked into the NSIS template generated by
; cargo-packager via the `nsis.installer-hooks` key in
; `crates/neoethos-app/Cargo.toml` (alongside vc_redist_install.nsh).
;
; Why this exists:
;   The full GGUF is ~5 GB. GitHub Releases caps single assets at 2 GB,
;   so the installer (~250 MB) ships WITHOUT the model and pulls it down
;   during install. End-user UX: one download (the installer), one
;   double-click, walk-away during install, come back to a working app
;   with AI Helper + News fully wired. Distribution-wise: the installer
;   stays GitHub-Releases-compatible.
;
; What it does:
;   1. Checks if $INSTDIR\resources\models\Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q4_K_M.gguf
;      already exists with a reasonable size (>= 4.5 GiB) — operator might have
;      pre-staged the file via fetch-gemma-model.ps1, in which case we
;      skip the download.
;   2. Verifies the install drive has at least 6 GiB free.
;   3. Uses inetc::get to download the GGUF with a visible progress dialog,
;      retry on transient failures, and resume on partial files. Lands the
;      bytes into $INSTDIR\resources\models\<filename>.
;   4. On download failure OR user cancel: shows a non-fatal warning. The
;      Flutter AI Helper screen has a first-launch downloader fallback that
;      will offer the same fetch from inside the running app, so a failed
;      install-time download does NOT block the rest of the application.
;   5. Future enhancement (commented out below): SHA256 verification via
;      the System::Call CryptoAPI helper or the `crypto` plugin. Disabled
;      for now because the upstream HF hash changes when HauhauCS re-uploads.

!define NEOETHOS_GEMMA_FILENAME "Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q4_K_M.gguf"
!define NEOETHOS_GEMMA_URL "https://huggingface.co/HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive/resolve/main/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q4_K_M.gguf"
; Minimum-acceptable size of a fully-downloaded GGUF in bytes — files
; smaller than this on disk are treated as partial downloads and re-fetched.
; Actual file is ~5.34 GB; 4.5 GiB threshold catches any meaningful truncation.
!define NEOETHOS_GEMMA_MIN_BYTES "4831838208"
; Free-space margin in MB we require on the install drive before kicking
; off the download. 6144 MB = 6 GiB; covers the 5 GiB model + headroom
; for the partial-file workspace + transient NSIS plugin scratch space.
!define NEOETHOS_GEMMA_MIN_FREE_MB "6144"

!macro NEOETHOS_FETCH_GEMMA_MODEL
    DetailPrint ""
    DetailPrint "=== NeoEthos: AI Helper model setup ==="

    StrCpy $0 "$INSTDIR\resources\models\${NEOETHOS_GEMMA_FILENAME}"
    StrCpy $R0 "$INSTDIR\resources\models"

    ; Make sure the destination dir exists. Idempotent — NSIS no-ops if it does.
    CreateDirectory "$R0"

    ; ── Step 1: skip if a complete-looking GGUF is already in place ────────
    IfFileExists "$0" 0 gemma_need_download
        ; Check size — partial downloads on a re-install would otherwise be
        ; accepted as valid and AI Helper would crash on first prompt.
        ${GetSize} "$R0" "/M=${NEOETHOS_GEMMA_FILENAME} /S=0B" $1 $2 $3
        IntCmpU $1 ${NEOETHOS_GEMMA_MIN_BYTES} gemma_already_present gemma_partial_file gemma_already_present

    gemma_partial_file:
        DetailPrint "  → Found partial GGUF (size=$1 bytes < ${NEOETHOS_GEMMA_MIN_BYTES}); re-fetching."
        Delete "$0"
        Goto gemma_need_download

    gemma_already_present:
        DetailPrint "  → GGUF already present and full-size. Skipping download."
        Goto gemma_setup_done

    ; ── Step 2: free-space pre-check ───────────────────────────────────────
    gemma_need_download:
        ; Read free MB on the install drive into $1.
        ; ${GetDrives} would also work; this is the simplest.
        StrCpy $2 "$INSTDIR" 2     ; e.g. "C:"
        System::Call 'kernel32::GetDiskFreeSpaceEx(t "$2\", *l .r3, *l .r4, *l .r5)'
        ; $3 = available bytes; convert to MB.
        System::Int64Op $3 / 1048576
        Pop $1
        DetailPrint "  → Free space on $2: $1 MB (need ${NEOETHOS_GEMMA_MIN_FREE_MB} MB)"
        IntCmpU $1 ${NEOETHOS_GEMMA_MIN_FREE_MB} gemma_have_space gemma_low_space gemma_have_space

    gemma_low_space:
        MessageBox MB_OKCANCEL|MB_ICONEXCLAMATION "Not enough free space on $2 to install the AI model (~5 GiB).$\r$\n$\r$\nFree space: $1 MB$\r$\nRequired:   ${NEOETHOS_GEMMA_MIN_FREE_MB} MB$\r$\n$\r$\nClick OK to skip the model download (NeoEthos will still work; AI Helper + News will offer to fetch the model on first run).$\r$\nClick Cancel to abort the entire install." IDOK gemma_skip_with_warning
        Abort

    gemma_have_space:
        ; ── Step 3: download with progress UI ──────────────────────────────
        ; inetc::get is the standard NSIS plugin for HTTPS downloads with a
        ; progress dialog. /POPUP "" gives a standalone "Downloading..."
        ; window separate from the main NSIS UI; /RESUME enables HTTP Range
        ; resumption if the connection drops and we re-launch the macro.
        DetailPrint "  → Downloading ${NEOETHOS_GEMMA_FILENAME} (~5 GiB)..."
        DetailPrint "    From: ${NEOETHOS_GEMMA_URL}"
        DetailPrint "    To:   $0"
        inetc::get /CAPTION "Downloading NeoEthos AI model (Gemma 4)" /POPUP "" /RESUME "Lost connection — resume download?" "${NEOETHOS_GEMMA_URL}" "$0" /END
        Pop $1
        StrCmp $1 "OK" gemma_download_ok
        StrCmp $1 "Cancelled" gemma_user_cancel
        ; Any other return = transport failure.
        DetailPrint "  → Download failed: $1"
        MessageBox MB_OK|MB_ICONEXCLAMATION "AI model download failed: $1.$\r$\n$\r$\nNeoEthos will still install successfully. The AI Helper screen has a one-click fetch button that will retry the download the first time you open it." /SD IDOK
        ; Don't abort — the Flutter first-launch downloader handles this case.
        Delete "$0"
        Goto gemma_setup_done

    gemma_user_cancel:
        DetailPrint "  → User cancelled the model download."
        Delete "$0"
        MessageBox MB_OK|MB_ICONINFORMATION "AI model download skipped.$\r$\n$\r$\nOpen the AI Helper screen anytime to fetch the model — there is a one-click downloader inside the app." /SD IDOK
        Goto gemma_setup_done

    gemma_download_ok:
        DetailPrint "  → Download complete: $0"
        ; Sanity-check size again now that we own the bytes.
        ${GetSize} "$R0" "/M=${NEOETHOS_GEMMA_FILENAME} /S=0B" $1 $2 $3
        IntCmpU $1 ${NEOETHOS_GEMMA_MIN_BYTES} gemma_size_ok gemma_size_bad gemma_size_ok
    gemma_size_bad:
        DetailPrint "  → Downloaded file is undersized ($1 bytes); marking as partial."
        Delete "$0"
        MessageBox MB_OK|MB_ICONEXCLAMATION "AI model download finished but the file is smaller than expected ($1 bytes). It has been removed; the AI Helper screen will offer to retry the download." /SD IDOK
        Goto gemma_setup_done
    gemma_size_ok:
        DetailPrint "  → Model size verified (${NEOETHOS_GEMMA_MIN_BYTES}+ bytes)."
        Goto gemma_setup_done

    gemma_skip_with_warning:
        DetailPrint "  → User opted to skip model download due to low disk space."
        Goto gemma_setup_done

    gemma_setup_done:
        DetailPrint "=== AI Helper model setup complete ==="
        DetailPrint ""
!macroend
