# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: kosred.neoethos
PackageVersion: 0.4.20
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - neoethos
ReleaseDate: 2026-05-23
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    Scope: user
    InstallerUrl: https://github.com/kosred/neoethos/releases/download/v0.4.20/neoethos_0.4.20_x64-setup.exe
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
ManifestType: installer
ManifestVersion: 1.6.0
